# Generated by Django 2.0.3 on 2018-03-11 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reg_guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
